version: 2.1
orbs:
  cypress: cypress-io/cypress@1.28.0
workflows:
  test-and-deploy:
    jobs:
      - cypress/run:
        start: npm start
      - deploy:
        requires:
          - cypress/run
        run: curl -X POST -d '{}' ${hook}
