version: 2.1
orbs:
  cypress: cypress-io/cypress@1.28.0
workflows:
  example-workflow:
    jobs:
      - cypress/run:
        start: npm start
      - deploy:
        command: curl -X POST -d '{}' ${hook}
