version: 2.1
orbs:
  cypress: cypress-io/cypress@1.28.0
workflows:
  example-workflow:
    jobs:
      - cypress/run:
          start: npm start
      - run:
        name: Deploy to Netlify
        command: curl -X POST -d '{}' ${hook}
